{{- if .Values.imagesPullSecret.secretName }}
{{- $registryAuthDocument := dict -}}
{{- $_ := set $registryAuthDocument "username" .Values.imagesPullSecret.username }}
{{- $_ := set $registryAuthDocument "password" .Values.imagesPullSecret.password }}
{{- $authMessage := printf "%s:%s" $registryAuthDocument.username $registryAuthDocument.password | b64enc }}
{{- $_ := set $registryAuthDocument "auth" $authMessage }}
{{- $dockerAuthDocument := dict .Values.imagesPullSecret.registryURL $registryAuthDocument }}
{{- $dockerConfigJSONDocument := dict "auths" $dockerAuthDocument -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagesPullSecret.secretName }}
  {{- if .Values.imagesPullSecret.annotations }}
  annotations: {{- toYaml .Values.imagesPullSecret.annotations | nindent 4 }}
  {{- end }}
  {{- if .Values.imagesPullSecret.labels }}
  labels: {{- toYaml .Values.imagesPullSecret.labels | nindent 4 }}
  {{- end }}
data:
  .dockerconfigjson: {{ $dockerConfigJSONDocument | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}
